- name: Deploy Consul Servers
  hosts: edge
  tasks:
  - name: Pull image
    shell: "docker pull {{docker.registry}}whisk/consul:{{docker_image_tag}}"
    when: docker.registry != ""
  - name: (Re)start consul server
    docker:
      name: consul
      image: "{{docker.registry}}whisk/consul:{{docker_image_tag}}"
      state: reloaded
      command: /startconsulserver.sh
      restart_policy: "{{docker.restart.policy}}"
      volumes:
        - "{{whisk.logs.dir}}/consul-server:/logs"
      ports:
        - "{{consul.port5}}:53"
        - "{{consul.port4}}:8500"
  - name: Wait until Consul Server is up and running
    wait_for: delay=5 host={{ansible_host}} port={{consul.port4}} timeout=60
  - name: Fill in whisk.properties
    local_action: command python "{{playbook_dir}}/../../tools/health/kvstore" --import -d "{{playbook_dir}}/../../"

- name: Deploy Consul Registrators
  hosts: all
  tasks:
  - name: (Re)start registrator
    docker:
      name: registrator
      image: gliderlabs/registrator
      state: reloaded
      restart_policy: "{{docker.restart.policy}}"
      log_driver: syslog
      volumes:
        - "{{whisk.logs.dir}}/consul-server:/logs"
        - "/var/run/docker.sock:/tmp/docker.sock"
      command: "-ip {{ansible_host}} -resync 2 consul://{{consul.host}}:{{consul.port4}}"
